name: ItchIo Deploy Workflow (WASM)

on:
  pull_request:
    branches:
      - main
    paths:
      - PongGame/multiplayer/**
  workflow_dispatch:

jobs:
  itchio-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: PongGame/multiplayer

    steps:
      # Step to checkout code from the repository
      - uses: actions/checkout@v3
        name: Checkout Code

      # Step to set up Go version
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      # Step to install Go dependencies
      - name: Install Go dependencies
        run: go mod tidy

      # Step to build the Go application as WebAssembly
      - name: Build the game for WebAssembly (WASM)
        run: |
          GOOS=js GOARCH=wasm go build -o dist/pong-game.wasm PongGame/multiplayer/main.go

      # Step to publish to Itch.io as a web game (WASM)
      - name: Publish to Itch.io (WASM)
        uses: manleydev/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCHIO_API_KEY }}
          CHANNEL: html          # Set up for Web/HTML
          ITCH_GAME: pong-game   # Your game name on Itch.io
          ITCH_USER: thisismemukul    # Your Itch.io username
          PACKAGE: PongGame/multiplayer/dist