name: ItchIo deploy workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - PongGame/multiplayer/**
  workflow_dispatch:

jobs:
  itchio-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: PongGame/multiplayer  # Change the working directory to PongGame/multiplayer

    steps:
      # Step to checkout code from the repository
      - uses: actions/checkout@v3
        name: Checkout Code

      # Step to set up Go version
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4  # Ensure this is the version your project needs

      # Step to install dependencies for Go
      - name: Install Go dependencies
        run: go mod tidy

      # Step to install system dependencies required by Ebiten (audio and graphical support)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev \
            libasound2-dev \
            pkg-config

      # Step to build the Go application (will generate the `dist` directory)
      - name: Build the game
        run: |
          mkdir -p dist   # Create the dist directory if it does not exist
          go build -o dist/pong-game main.go  # Build the Go application in the dist directory

      # Step to publish the build to Itch.io
      - name: Publish to Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCHIO_API_KEY }}
          CHANNEL: HTML           # Change to your required channel
          ITCH_GAME: pong-game    # Your Itch.io game name
          ITCH_USER: thisismemukul     # Replace with your Itch.io username
          PACKAGE: PongGame/multiplayer/dist  # The dist folder to be published